SET C51INC=D:\program files\keil\C51\Inc;D:\program files\keil\C51\Inc\STC
SET C51LIB=D:\program files\keil\C51\Lib
SET CPU_TYPE=STC15F2K60S2
SET CPU_VENDOR=STC
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x02160EC0
"D:\program files\keil\C51\BIN\A51.EXE" @".\Objects\STARTUP._ia"
"D:\program files\keil\C51\BIN\C51.EXE" @".\Objects\main.__i"
"D:\program files\keil\C51\BIN\C51.EXE" @".\Objects\PIO_1.__i"
"D:\program files\keil\C51\BIN\C51.EXE" @".\Objects\gpio.__i"
"D:\program files\keil\C51\BIN\C51.EXE" @".\Objects\STEPMO~1.__I"
"D:\program files\keil\C51\BIN\C51.EXE" @".\Objects\delay.__i"
"D:\program files\keil\C51\BIN\C51.EXE" @".\Objects\timer.__i"
"D:\program files\keil\C51\BIN\C51.EXE" @".\Objects\89C51_it.__i"
"D:\program files\keil\C51\BIN\C51.EXE" @".\Objects\usart.__i"
"D:\program files\keil\C51\BIN\C51.EXE" @".\Objects\HD7279.__i"
"D:\program files\keil\C51\BIN\C51.EXE" @".\Objects\8255.__i"
"D:\program files\keil\C51\BIN\C51.EXE" @".\Objects\8254.__i"
"D:\program files\keil\C51\BIN\C51.EXE" @".\Objects\key.__i"
"D:\program files\keil\C51\BIN\C51.EXE" @".\Objects\adc.__i"
"D:\program files\keil\C51\BIN\BL51.EXE" @".\Objects\C81.lnp"
"D:\program files\keil\C51\BIN\OH51.EXE" ".\Objects\C81" 
